/*!
 * Theia Sticky Sidebar v1.4.0
 * https://github.com/WeCodePixels/theia-sticky-sidebar
 *
 * Glues your website's sidebars, making them permanently visible while scrolling.
 *
 * Copyright 2013-2016 WeCodePixels and other contributors
 * Released under the MIT license
 */

(function(d){d.fn.theiaStickySidebar=function(c){function g(f,c){if(!0===f.initialized)return!0;if(d("body").width()<f.minWidth)return!1;p(f,c);return!0}function p(f,c){f.initialized=!0;d("head").append(d('<style>.theiaStickySidebar:after {content: ""; display: table; clear: both;}</style>'));c.each(function(){function c(){a.fixedScrollTop=0;a.sidebar.css({"min-height":"1px"});a.stickySidebar.css({position:"static",width:""})}function q(b){var a=b.height();b.children().each(function(){a=Math.max(a,
d(this).height())});return a}var a={};a.sidebar=d(this);a.options=f||{};a.container=d(a.options.containerSelector);0==a.container.length&&(a.container=a.sidebar.parent());a.sidebar.parents().css("-webkit-transform","none");a.sidebar.css({position:"relative",overflow:"visible","-webkit-box-sizing":"border-box","-moz-box-sizing":"border-box","box-sizing":"border-box"});a.stickySidebar=a.sidebar.find(".theiaStickySidebar");if(0==a.stickySidebar.length){var g=/(?:text|application)\/(?:x-)?(?:javascript|ecmascript)/i;
a.sidebar.find("script").filter(function(b,a){return 0===a.type.length||a.type.match(g)}).remove();a.stickySidebar=d("<div>").addClass("theiaStickySidebar").append(a.sidebar.children());a.sidebar.append(a.stickySidebar)}a.marginTop=parseInt(a.sidebar.css("margin-top"));a.marginBottom=parseInt(a.sidebar.css("margin-bottom"));a.paddingTop=parseInt(a.sidebar.css("padding-top"));a.paddingBottom=parseInt(a.sidebar.css("padding-bottom"));var h=a.stickySidebar.offset().top,m=a.stickySidebar.outerHeight();
a.stickySidebar.css("padding-top",1);a.stickySidebar.css("padding-bottom",1);h-=a.stickySidebar.offset().top;m=a.stickySidebar.outerHeight()-m-h;0==h?(a.stickySidebar.css("padding-top",0),a.stickySidebarPaddingTop=0):a.stickySidebarPaddingTop=1;0==m?(a.stickySidebar.css("padding-bottom",0),a.stickySidebarPaddingBottom=0):a.stickySidebarPaddingBottom=1;a.previousScrollTop=null;a.fixedScrollTop=0;c();a.onScroll=function(b){if(b.stickySidebar.is(":visible"))if(d("body").width()<b.options.minWidth)c();
else if(b.options.disableOnResponsiveLayouts&&b.sidebar.outerWidth("none"==b.sidebar.css("float"))+50>b.container.width())c();else{var a=d(document).scrollTop(),l="static";if(a>=b.container.offset().top+(b.paddingTop+b.marginTop-b.options.additionalMarginTop)){var k=b.paddingTop+b.marginTop+f.additionalMarginTop,h=b.paddingBottom+b.marginBottom+f.additionalMarginBottom,g=b.container.offset().top,e=b.container.offset().top+q(b.container),l=0+f.additionalMarginTop,k=b.stickySidebar.outerHeight()+k+
h<d(window).height()?l+b.stickySidebar.outerHeight():d(window).height()-b.marginBottom-b.paddingBottom-f.additionalMarginBottom,g=g-a+b.paddingTop+b.marginTop,h=e-a-b.paddingBottom-b.marginBottom,e=b.stickySidebar.offset().top-a,n=b.previousScrollTop-a;"fixed"==b.stickySidebar.css("position")&&"modern"==b.options.sidebarBehavior&&(e+=n);"stick-to-top"==b.options.sidebarBehavior&&(e=f.additionalMarginTop);"stick-to-bottom"==b.options.sidebarBehavior&&(e=k-b.stickySidebar.outerHeight());e=0<n?Math.min(e,
l):Math.max(e,k-b.stickySidebar.outerHeight());e=Math.max(e,g);e=Math.min(e,h-b.stickySidebar.outerHeight());l=(g=b.container.height()==b.stickySidebar.outerHeight())||e!=l?g||e!=k-b.stickySidebar.outerHeight()?a+e-b.sidebar.offset().top-b.paddingTop<=f.additionalMarginTop?"static":"absolute":"fixed":"fixed"}"fixed"==l?b.stickySidebar.css({position:"fixed",width:b.sidebar.width(),top:e,left:b.sidebar.offset().left+parseInt(b.sidebar.css("padding-left"))}):"absolute"==l?(k={},"absolute"!=b.stickySidebar.css("position")&&
(k.position="absolute",k.top=a+e-b.sidebar.offset().top-b.stickySidebarPaddingTop-b.stickySidebarPaddingBottom),k.width=b.sidebar.width(),k.left="",b.stickySidebar.css(k)):"static"==l&&c();"static"!=l&&1==b.options.updateSidebarHeight&&b.sidebar.css({"min-height":b.stickySidebar.outerHeight()+b.stickySidebar.offset().top-b.sidebar.offset().top+b.paddingBottom});b.previousScrollTop=a}};a.onScroll(a);d(document).scroll(function(a){return function(){a.onScroll(a)}}(a));d(window).resize(function(a){return function(){a.stickySidebar.css({position:"static"});
a.onScroll(a)}}(a))})}c=d.extend({containerSelector:"",additionalMarginTop:0,additionalMarginBottom:0,updateSidebarHeight:!0,minWidth:0,disableOnResponsiveLayouts:!0,sidebarBehavior:"modern"},c);c.additionalMarginTop=parseInt(c.additionalMarginTop)||0;c.additionalMarginBottom=parseInt(c.additionalMarginBottom)||0;(function(c,h){g(c,h)||(console.log("TST: Body width smaller than options.minWidth. Init is delayed."),d(document).scroll(function(c,f){return function(a){g(c,f)&&d(this).unbind(a)}}(c,h)),
d(window).resize(function(c,f){return function(a){g(c,f)&&d(this).unbind(a)}}(c,h)))})(c,this)}})(jQuery);jQuery(document).ready(function(){jQuery("cont.flol, aside.sdbr.flor").theiaStickySidebar({additionalMarginTop:40})});